Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
discarding /work/opt/anaconda/py35/bin from PATH
prepending /home/s1510756/py27/bin to PATH
Requirement already satisfied: enum34==1.1.2 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 1))
Requirement already satisfied: matplotlib==1.5.1 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 2))
Requirement already satisfied: numpy==1.10.4 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 3))
Requirement already satisfied: scipy==0.17.0 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 4))
Requirement already satisfied: scikit-learn==0.17.1 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 5))
Requirement already satisfied: psycopg2==2.6.1 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 6))
Requirement already satisfied: unidiff==0.5.2 in ./py27/lib/python2.7/site-packages (from -r /home/s1510756/hpcc/requirements.txt (line 7))
Requirement already satisfied: python-dateutil in ./py27/lib/python2.7/site-packages (from matplotlib==1.5.1->-r /home/s1510756/hpcc/requirements.txt (line 2))
Requirement already satisfied: pytz in ./py27/lib/python2.7/site-packages (from matplotlib==1.5.1->-r /home/s1510756/hpcc/requirements.txt (line 2))
Requirement already satisfied: cycler in ./py27/lib/python2.7/site-packages (from matplotlib==1.5.1->-r /home/s1510756/hpcc/requirements.txt (line 2))
Requirement already satisfied: pyparsing!=2.0.4,>=1.5.6 in ./py27/lib/python2.7/site-packages (from matplotlib==1.5.1->-r /home/s1510756/hpcc/requirements.txt (line 2))
Requirement already satisfied: six>=1.5 in ./py27/lib/python2.7/site-packages (from python-dateutil->matplotlib==1.5.1->-r /home/s1510756/hpcc/requirements.txt (line 2))
Started loading data
Data loaded #175704
Start extracting lines...
Completed extracting lines including #180 invalid patches.
Traceback (most recent call last):
  File "/home/s1510756/hpcc/vcc-combine.py", line 78, in <module>
    X = vectorized.toarray()
  File "/home/s1510756/py27/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 940, in toarray
    return self.tocoo(copy=False).toarray(order=order, out=out)
  File "/home/s1510756/py27/lib/python2.7/site-packages/scipy/sparse/coo.py", line 250, in toarray
    B = self._process_toarray_args(order, out)
  File "/home/s1510756/py27/lib/python2.7/site-packages/scipy/sparse/base.py", line 817, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError
